target("epix-window")
    set_kind("static")
    add_files("src/*.cpp")
    add_includedirs("include", { public = true })
    add_deps("epix-common", "epix-app", "epix-assets", "epix-input")
    set_options("epix_config")
    add_packages("glfw", { public = true })
target_end()