epix_add_module(epix_mesh)
target_link_libraries(epix_mesh PUBLIC epix_common)
target_link_libraries(epix_mesh PUBLIC epix_ecs)
target_link_libraries(epix_mesh PUBLIC epix_app)
target_link_libraries(epix_mesh PUBLIC epix_assets)
target_link_libraries(epix_mesh PUBLIC epix_transform)
target_link_libraries(epix_mesh PUBLIC glm::glm)
target_link_libraries(epix_mesh PUBLIC webgpu)

epix_add_tests(mesh LINK_LIBS epix_mesh)
