module;

#include <SFML/Window/Keyboard.hpp>
#include <SFML/Window/Mouse.hpp>

module epix.sfml.core;

input::KeyCode sfml::map_sfml_key_to_input(sf::Keyboard::Key key) {
    switch (key) {
        case sf::Keyboard::Key::A:
            return input::KeyCode::KeyA;
        case sf::Keyboard::Key::B:
            return input::KeyCode::KeyB;
        case sf::Keyboard::Key::C:
            return input::KeyCode::KeyC;
        case sf::Keyboard::Key::D:
            return input::KeyCode::KeyD;
        case sf::Keyboard::Key::E:
            return input::KeyCode::KeyE;
        case sf::Keyboard::Key::F:
            return input::KeyCode::KeyF;
        case sf::Keyboard::Key::G:
            return input::KeyCode::KeyG;
        case sf::Keyboard::Key::H:
            return input::KeyCode::KeyH;
        case sf::Keyboard::Key::I:
            return input::KeyCode::KeyI;
        case sf::Keyboard::Key::J:
            return input::KeyCode::KeyJ;
        case sf::Keyboard::Key::K:
            return input::KeyCode::KeyK;
        case sf::Keyboard::Key::L:
            return input::KeyCode::KeyL;
        case sf::Keyboard::Key::M:
            return input::KeyCode::KeyM;
        case sf::Keyboard::Key::N:
            return input::KeyCode::KeyN;
        case sf::Keyboard::Key::O:
            return input::KeyCode::KeyO;
        case sf::Keyboard::Key::P:
            return input::KeyCode::KeyP;
        case sf::Keyboard::Key::Q:
            return input::KeyCode::KeyQ;
        case sf::Keyboard::Key::R:
            return input::KeyCode::KeyR;
        case sf::Keyboard::Key::S:
            return input::KeyCode::KeyS;
        case sf::Keyboard::Key::T:
            return input::KeyCode::KeyT;
        case sf::Keyboard::Key::U:
            return input::KeyCode::KeyU;
        case sf::Keyboard::Key::V:
            return input::KeyCode::KeyV;
        case sf::Keyboard::Key::W:
            return input::KeyCode::KeyW;
        case sf::Keyboard::Key::X:
            return input::KeyCode::KeyX;
        case sf::Keyboard::Key::Y:
            return input::KeyCode::KeyY;
        case sf::Keyboard::Key::Z:
            return input::KeyCode::KeyZ;
        case sf::Keyboard::Key::Num0:
            return input::KeyCode::Key0;
        case sf::Keyboard::Key::Num1:
            return input::KeyCode::Key1;
        case sf::Keyboard::Key::Num2:
            return input::KeyCode::Key2;
        case sf::Keyboard::Key::Num3:
            return input::KeyCode::Key3;
        case sf::Keyboard::Key::Num4:
            return input::KeyCode::Key4;
        case sf::Keyboard::Key::Num5:
            return input::KeyCode::Key5;
        case sf::Keyboard::Key::Num6:
            return input::KeyCode::Key6;
        case sf::Keyboard::Key::Num7:
            return input::KeyCode::Key7;
        case sf::Keyboard::Key::Num8:
            return input::KeyCode::Key8;
        case sf::Keyboard::Key::Num9:
            return input::KeyCode::Key9;
        case sf::Keyboard::Key::Escape:
            return input::KeyCode::KeyEscape;
        case sf::Keyboard::Key::LControl:
            return input::KeyCode::KeyLeftControl;
        case sf::Keyboard::Key::LShift:
            return input::KeyCode::KeyLeftShift;
        case sf::Keyboard::Key::LAlt:
            return input::KeyCode::KeyLeftAlt;
        case sf::Keyboard::Key::LSystem:
            return input::KeyCode::KeyLeftSuper;
        case sf::Keyboard::Key::RControl:
            return input::KeyCode::KeyRightControl;
        case sf::Keyboard::Key::RShift:
            return input::KeyCode::KeyRightShift;
        case sf::Keyboard::Key::RAlt:
            return input::KeyCode::KeyRightAlt;
        case sf::Keyboard::Key::RSystem:
            return input::KeyCode::KeyRightSuper;
        case sf::Keyboard::Key::Menu:
            return input::KeyCode::KeyMenu;
        case sf::Keyboard::Key::LBracket:
            return input::KeyCode::KeyLeftBracket;
        case sf::Keyboard::Key::RBracket:
            return input::KeyCode::KeyRightBracket;
        case sf::Keyboard::Key::Semicolon:
            return input::KeyCode::KeySemicolon;
        case sf::Keyboard::Key::Comma:
            return input::KeyCode::KeyComma;
        case sf::Keyboard::Key::Period:
            return input::KeyCode::KeyPeriod;
        case sf::Keyboard::Key::Apostrophe:
            return input::KeyCode::KeyApostrophe;
        case sf::Keyboard::Key::Slash:
            return input::KeyCode::KeySlash;
        case sf::Keyboard::Key::Backslash:
            return input::KeyCode::KeyBackslash;
        case sf::Keyboard::Key::Grave:
            return input::KeyCode::KeyGraveAccent;
        case sf::Keyboard::Key::Equal:
            return input::KeyCode::KeyEqual;
        case sf::Keyboard::Key::Hyphen:
            return input::KeyCode::KeyMinus;
        case sf::Keyboard::Key::Space:
            return input::KeyCode::KeySpace;
        case sf::Keyboard::Key::Enter:
            return input::KeyCode::KeyEnter;
        case sf::Keyboard::Key::Backspace:
            return input::KeyCode::KeyBackspace;
        case sf::Keyboard::Key::Tab:
            return input::KeyCode::KeyTab;
        case sf::Keyboard::Key::PageUp:
            return input::KeyCode::KeyPageUp;
        case sf::Keyboard::Key::PageDown:
            return input::KeyCode::KeyPageDown;
        case sf::Keyboard::Key::End:
            return input::KeyCode::KeyEnd;
        case sf::Keyboard::Key::Home:
            return input::KeyCode::KeyHome;
        case sf::Keyboard::Key::Insert:
            return input::KeyCode::KeyInsert;
        case sf::Keyboard::Key::Delete:
            return input::KeyCode::KeyDelete;
        case sf::Keyboard::Key::Add:
            return input::KeyCode::KeyKpAdd;
        case sf::Keyboard::Key::Subtract:
            return input::KeyCode::KeyKpSubtract;
        case sf::Keyboard::Key::Multiply:
            return input::KeyCode::KeyKpMultiply;
        case sf::Keyboard::Key::Divide:
            return input::KeyCode::KeyKpDivide;
        case sf::Keyboard::Key::Left:
            return input::KeyCode::KeyLeft;
        case sf::Keyboard::Key::Right:
            return input::KeyCode::KeyRight;
        case sf::Keyboard::Key::Up:
            return input::KeyCode::KeyUp;
        case sf::Keyboard::Key::Down:
            return input::KeyCode::KeyDown;
        case sf::Keyboard::Key::Numpad0:
            return input::KeyCode::KeyKp0;
        case sf::Keyboard::Key::Numpad1:
            return input::KeyCode::KeyKp1;
        case sf::Keyboard::Key::Numpad2:
            return input::KeyCode::KeyKp2;
        case sf::Keyboard::Key::Numpad3:
            return input::KeyCode::KeyKp3;
        case sf::Keyboard::Key::Numpad4:
            return input::KeyCode::KeyKp4;
        case sf::Keyboard::Key::Numpad5:
            return input::KeyCode::KeyKp5;
        case sf::Keyboard::Key::Numpad6:
            return input::KeyCode::KeyKp6;
        case sf::Keyboard::Key::Numpad7:
            return input::KeyCode::KeyKp7;
        case sf::Keyboard::Key::Numpad8:
            return input::KeyCode::KeyKp8;
        case sf::Keyboard::Key::Numpad9:
            return input::KeyCode::KeyKp9;
        case sf::Keyboard::Key::F1:
            return input::KeyCode::KeyF1;
        case sf::Keyboard::Key::F2:
            return input::KeyCode::KeyF2;
        case sf::Keyboard::Key::F3:
            return input::KeyCode::KeyF3;
        case sf::Keyboard::Key::F4:
            return input::KeyCode::KeyF4;
        case sf::Keyboard::Key::F5:
            return input::KeyCode::KeyF5;
        case sf::Keyboard::Key::F6:
            return input::KeyCode::KeyF6;
        case sf::Keyboard::Key::F7:
            return input::KeyCode::KeyF7;
        case sf::Keyboard::Key::F8:
            return input::KeyCode::KeyF8;
        case sf::Keyboard::Key::F9:
            return input::KeyCode::KeyF9;
        case sf::Keyboard::Key::F10:
            return input::KeyCode::KeyF10;
        case sf::Keyboard::Key::F11:
            return input::KeyCode::KeyF11;
        case sf::Keyboard::Key::F12:
            return input::KeyCode::KeyF12;
        case sf::Keyboard::Key::F13:
            return input::KeyCode::KeyF13;
        case sf::Keyboard::Key::F14:
            return input::KeyCode::KeyF14;
        case sf::Keyboard::Key::F15:
            return input::KeyCode::KeyF15;
        case sf::Keyboard::Key::Pause:
            return input::KeyCode::KeyPause;
        default:
            return input::KeyCode::KeyUnknown;
    }
}

input::MouseButton sfml::map_sfml_mouse_button_to_input(sf::Mouse::Button button) {
    switch (button) {
        case sf::Mouse::Button::Left:
            return input::MouseButton::MouseButton1;
        case sf::Mouse::Button::Right:
            return input::MouseButton::MouseButton2;
        case sf::Mouse::Button::Middle:
            return input::MouseButton::MouseButton3;
        case sf::Mouse::Button::Extra1:
            return input::MouseButton::MouseButton4;
        case sf::Mouse::Button::Extra2:
            return input::MouseButton::MouseButton5;
        default:
            return input::MouseButton::MouseButtonUnknown;
    }
}
