target("epix-input")
    set_kind("static")
    add_files("src/*.cpp")
    add_includedirs("include", { public = true })
    add_deps("epix-common", "epix-app")
    set_options("epix_config")
target_end()