epix_add_module(epix_ecs)
target_link_libraries(epix_ecs PUBLIC epix_common)
target_link_libraries(epix_ecs PUBLIC spdlog::spdlog)
target_link_libraries(epix_ecs PUBLIC epix_task)
target_link_libraries(epix_ecs PUBLIC epix_utils)
target_link_libraries(epix_ecs PRIVATE Taskflow)
target_link_libraries(epix_ecs PUBLIC BSThreadPool)
if (CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang" AND NOT WIN32)
  target_link_libraries(epix_ecs PUBLIC stdc++exp)
endif()
if (EPIX_ENABLE_TRACY)
  target_compile_definitions(epix_ecs PRIVATE EPIX_ENABLE_TRACY)
  target_link_libraries(epix_ecs PRIVATE TracyClient)
endif()

epix_add_tests(core LINK_LIBS epix_ecs)