if (EPIX_IMPORT_STD AND NOT EPIX_CXX_MODULE)
  message(WARNING "EPIX_IMPORT_STD option requires EPIX_CXX_MODULE to be enabled. Disabling EPIX_IMPORT_STD.")
  set(EPIX_IMPORT_STD OFF)
endif()

if (EPIX_IMPORT_STD)
  set(CMAKE_CXX_MODULE_STD ON)
  if (CMAKE_VERSION VERSION_LESS "3.30")
    message(FATAL_ERROR "CMake version is less than 3.30, C++23 standard library modules support may be incomplete.")
  else()
    if (CMAKE_VERSION VERSION_GREATER_EQUAL "4.3.0")
      set(CXX_IMPORT_STD_UUID "451f2fe2-a8a2-47c3-bc32-94786d8fc91b")
    elseif (CMAKE_VERSION VERSION_GREATER_EQUAL "4.0.3")
      set(CXX_IMPORT_STD_UUID "d0edc3af-4c50-42ea-a356-e2862fe7a444")
    elseif (CMAKE_VERSION VERSION_GREATER_EQUAL "4.0.0")
      set(CXX_IMPORT_STD_UUID "a9e1cf81-9932-4810-974b-6eccaf14e457")
    elseif (CMAKE_VERSION VERSION_GREATER_EQUAL "3.31.8")
      set(CXX_IMPORT_STD_UUID "d0edc3af-4c50-42ea-a356-e2862fe7a444")
    elseif (CMAKE_VERSION VERSION_GREATER_EQUAL "3.30.0")
      set(CXX_IMPORT_STD_UUID "0e5b6991-d74f-4b3d-a41c-cf096e0b2508")
    endif()
    message(STATUS "CMake experimental import std uuid = ${CXX_IMPORT_STD_UUID}")
    set(CMAKE_EXPERIMENTAL_CXX_IMPORT_STD ${CXX_IMPORT_STD_UUID} CACHE STRING "Enable CxxImportStd experimental feature with UUID")

    cmake_language(GET_EXPERIMENTAL_FEATURE_ENABLED "CxxImportStd" _cxx_import_std_enabled)
    if (_cxx_import_std_enabled STREQUAL "TRUE")
      message(STATUS "Enabled CMake experimental feature 'CxxImportStd' using UUID: ${CMAKE_EXPERIMENTAL_CXX_IMPORT_STD}")
    else()
      message(FATAL_ERROR "Tried to enable CxxImportStd with UUID ${CMAKE_EXPERIMENTAL_CXX_IMPORT_STD} but CMake did not report it enabled.")
      unset(CMAKE_EXPERIMENTAL_CXX_IMPORT_STD CACHE)
    endif()
  endif()
endif()
