# Utility functions for WebGPU integration
# Based on patterns from WebGPU-distribution

# Detect system architecture
function(detect_system_architecture)
    if (CMAKE_SIZEOF_VOID_P EQUAL 8)
        if (CMAKE_SYSTEM_PROCESSOR MATCHES "aarch64|arm64|ARM64")
            set(ARCH "aarch64" PARENT_SCOPE)
        else()
            set(ARCH "x86_64" PARENT_SCOPE)
        endif()
    else()
        set(ARCH "i686" PARENT_SCOPE)
    endif()
endfunction()

# Build library filename based on platform and link type
function(build_lib_filename OUT_VAR LIB_NAME IS_SHARED)
    if (CMAKE_SYSTEM_NAME STREQUAL "Windows")
        if (IS_SHARED)
            set(${OUT_VAR} "${LIB_NAME}.dll" PARENT_SCOPE)
        else()
            if (MSVC)
                set(${OUT_VAR} "${LIB_NAME}.lib" PARENT_SCOPE)
            else()
                set(${OUT_VAR} "lib${LIB_NAME}.a" PARENT_SCOPE)
            endif()
        endif()
    elseif (CMAKE_SYSTEM_NAME STREQUAL "Darwin")
        if (IS_SHARED)
            set(${OUT_VAR} "lib${LIB_NAME}.dylib" PARENT_SCOPE)
        else()
            set(${OUT_VAR} "lib${LIB_NAME}.a" PARENT_SCOPE)
        endif()
    else()
        if (IS_SHARED)
            set(${OUT_VAR} "lib${LIB_NAME}.so" PARENT_SCOPE)
        else()
            set(${OUT_VAR} "lib${LIB_NAME}.a" PARENT_SCOPE)
        endif()
    endif()
endfunction()
